### PR TITLE
Adding NTP service configuration

### PR DESCRIPTION
**Pull request by mtnbikenc**
Setting TimeZone using 'defaults'
Starting and enabling ntpd
Opening the firewall for ntpd

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Need to add stuff for ntp config.  (restrict)

**Comment by mtnbikenc** [comment]
Need to add testing output.

**Comment by mtnbikenc** [comment]
Testing output for relevant tasks:
```

TASK: [base | Set the correct timezone] ***************************************
changed: [localhost]

TASK: [base | Configure NTP] **************************************************
changed: [localhost]

TASK: [base | copy iptables config file] **************************************
changed: [localhost]

TASK: [base | start & enable services] ****************************************
changed: [localhost] => (item=docker)
changed: [localhost] => (item=iptables)
changed: [localhost] => (item=ntpd)
```

**Comment by adean20csc** [comment]
Good  :+1:

**Comment by jcpowermac** [comment]
@mtnbikenc can you make sure that ntpd fuctions correctly?

```
➜  ~  ntpq -p 10.53.252.252
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
+zombie.frizzen. 208.75.88.4      3 u   90 1024  377   89.205   -4.388   1.975
-xen1.rack911.co 173.44.32.10     3 u  614 1024  377  109.317   -9.255   5.624
+vimo.dorui.net  209.51.161.238   2 u  373 1024  167   37.798   -1.182   4.061
*time-a.nist.gov .ACTS.           1 u  479 1024  177   36.780    0.374   2.521
```
or 
```
➜  ~  ntpdate -q 10.53.252.252
server 10.53.252.252, stratum 2, offset -0.000001, delay 0.02567
27 Aug 10:35:12 ntpdate[22468]: adjust time server 10.53.252.252 offset -0.000001 sec
```

**Comment by mtnbikenc** [comment]
NTP verification:
```
[root@localhost kragle]# ntpq -p 0.rhel.pool.ntp.org
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*time-b.nist.gov .ACTS.           1 u  894 1024  377   26.288    2.819   0.591
+time.devry.net  10.152.2.2       2 u  564 1024  377   10.647   -0.240   1.125
+74.117.238.11.r 0.240.150.188    3 u  885 1024  377    8.027   -1.947   0.813
-NTP1.playallian 129.6.15.28      2 u  872 1024  377   52.681   -0.816   0.494
[root@localhost kragle]# ntpdate -q 0.rhel.pool.ntp.org
server 69.167.160.102, stratum 2, offset -0.033562, delay 0.07538
server 173.230.144.109, stratum 2, offset -0.035694, delay 0.10980
server 172.82.134.51, stratum 2, offset -0.039049, delay 0.05676
server 204.2.134.163, stratum 2, offset -0.039714, delay 0.11748
27 Aug 10:41:27 ntpdate[46852]: adjust time server 172.82.134.51 offset -0.039049 sec
```

**Comment by jcpowermac** [comment]
Looks good :+1:

**Pull request merged**
