### PR TITLE
kragle - fixed changed variable

### PR DESCRIPTION
**Pull request by adean20csc**
Had to change a variable kragle_ to autodeploy_

### CODE REVIEW

**Comment by mtnbikenc** [comment]
I'm walking through a test build and will comment here when done.

**Comment by mtnbikenc** [comment]
I ended up getting three directories in /mnt/sdb; autodeploy, projects and resources.  The projects folder is empty and the resources folder has a tree but is empty.

**Comment by mtnbikenc** [comment]
Those extra directories were created while following manual steps in the doc.  @adean20csc has updated the doc.

**Comment by mtnbikenc** [comment]
Code review :+1:

**Comment by jcpowermac** [comment]
Code Review :+1:

**Pull request merged**
