### PR TITLE
kragle - moving things out of wiley

### PR DESCRIPTION
**Pull request by adean20csc**
These were all kragle related items that were in wiley
- site_discovery group_vars
- hanlon modules
- dhcp server role
- site_docker.yml
- site_discovery.yml

RESULTS:

 ansible-playbook ./ansible/site_docker.ymlPLAY [Start Hanlon Docker Environment] 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [Ansible Docker Requirements] ******************************************* 
changed: [localhost] => (item=six==1.4.1)
changed: [localhost] => (item=docker-py==1.1.0)
changed: [localhost] => (item=requests==2.7.0)

TASK: [Clean up existing containers] ****************************************** 
changed: [localhost] => (item={'image': 'mongo', 'name': 'hanlon-mongo'})
changed: [localhost] => (item={'image': 'cscdock/hanlon', 'name': 'hanlon-server'})
changed: [localhost] => (item={'image': 'cscdock/atftpd', 'name': 'hanlon-atftpd'})

TASK: [Start Mongo Container] ************************************************* 
changed: [localhost]

TASK: [Remove hanlon client config file] ************************************** 
ok: [localhost]

TASK: [Start Hanlon Server Container] ***************************************** 
changed: [localhost]

TASK: [Wait for Hanlon Server to start] *************************************** 
ok: [localhost]

TASK: [Start TFTP Server Container] ******************************************* 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=8    changed=5    unreachable=0    failed=0

### CODE REVIEW

**Comment by jcpowermac** [comment]
Code review :+1:

**Comment by mtnbikenc** [comment]
site_discovery.yml should be tested
The "Create SSH Key Pair for root user" task should probably be moved into the base role with the other ssh tasks.
The resulting dhcpd.conf file provided from site_discovery testing.

**Comment by adean20csc** [comment]
PLAY [Configure deployment node for site discovery] *************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [dhcp-server | install dhcp server package] ***************************** 
ok: [localhost]

TASK: [dhcp-server | setup dhcpd.conf] **************************************** 
ok: [localhost]

TASK: [dhcp-server | enable dhcpd service] ************************************ 
ok: [localhost]

TASK: [Create SSH Key Pair for root user] ************************************* 
ok: [localhost]

TASK: [Check for local copy of Hanlon Microkernel] **************************** 
ok: [localhost]

TASK: [Download Hanlon Microkernel] ******************************************* 
skipping: [localhost]

TASK: [Add a Microkernel Image to Hanlon] ************************************* 
changed: [localhost]

TASK: [Add a Discover Only Model to Hanlon] *********************************** 
changed: [localhost]

TASK: [Add a Discover Only Policy to Hanlon] ********************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=9    changed=3    unreachable=0    failed=0

**Comment by adean20csc** [comment]
[root@autodeploy /]# cat etc/dhcp/dhcpd.conf 
default lease-time 600;
max-lease-time 7200;

authoritative;

option hanlon_server code 224 = ip-address;
option hanlon_port code 225 = unsigned integer 16;
option hanlon_base_uri code 226 = text;

subnet 172.17.16.0 netmask 255.255.255.0 {
    range                       172.17.16.20 172.17.16.50;
    option routers              172.17.16.1;
    option subnet-mask          255.255.255.0;
    option domain-name          "lordbusiness";
    option domain-name-servers  192.168.70.3;
    next-server                 172.17.17.201;
    option tftp-server-name     "172.17.17.201";
    option hanlon_server        172.17.17.201;
    option hanlon_port          8026;
    option hanlon_base_uri      "/hanlon/api/v1";

    if exists user-class and option user-class = "iPXE" {
        filename "hanlon.ipxe";
    } else {
        filename "undionly.kpxe";
    }
}

**Comment by mtnbikenc** [comment]
Code review :+1:

**Comment by jcpowermac** [comment]
Good :+1:

**Pull request merged**
