### PR TITLE
Changes to git clone process to use ssh key

### PR DESCRIPTION
**Pull request by mtnbikenc**
This PR modifies the way git repos are cloned so that a username/password is not required, however a key file must be specified.  This change simplifies the way deployments can be performed by not requiring a user's GitHub password to be handed out.

The key file can be created like this:
```
cat << EOF > ~/github.pem
-----BEGIN RSA PRIVATE KEY-----
<insert_key_file_text_here>
-----END RSA PRIVATE KEY-----
EOF
chmod 0600 ~/github.pem
```

The key file location can then be specified using `extra-vars` at the command line.

initial_stage.yml testing:
```
[root@rhel72 ~]# ansible-playbook initial_stage.yml --extra-vars "github_key_file=~/github.pem"
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [Download the Kragle source repo] *****************************************

TASK [Create the staging directories] ******************************************
changed: [localhost] => (item=/opt/autodeploy/projects)
changed: [localhost] => (item=/opt/autodeploy/resources)

TASK [Clone the project repos from Git] ****************************************
changed: [localhost] => (item={u'repo': u'git@github.com:csc/kragle.git', u'name': u'kragle'})

TASK [Checkout the latest tagged version] **************************************
changed: [localhost] => (item={u'repo': u'git@github.com:csc/kragle.git', u'name': u'kragle'})

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=3    unreachable=0    failed=0
```

stage_resources.yml testing (effected tasks)
```
[root@rhel72 ansible]# ansible-playbook stage_resources.yml --extra-vars "github_key_file=~/github.pem rhn_user=$RHN_USER rhn_pass=$RHN_PASS"

...

TASK [Clone the project repos from Git] ****************************************
changed: [localhost] => (item={u'repo': u'git@github.com:csc/wiley.git', u'name': u'wiley'})
changed: [localhost] => (item={u'repo': u'git@github.com:csc/slimer.git', u'name': u'slimer'})
changed: [localhost] => (item={u'repo': u'git@github.com:csc/ansible-scaleio.git', u'name': u'ansible-scaleio'})

TASK [Checkout the latest tagged version] **************************************
changed: [localhost] => (item={u'repo': u'git@github.com:csc/wiley.git', u'name': u'wiley'})
changed: [localhost] => (item={u'repo': u'git@github.com:csc/slimer.git', u'name': u'slimer'})
changed: [localhost] => (item={u'repo': u'git@github.com:csc/ansible-scaleio.git', u'name': u'ansible-scaleio'})

...

PLAY RECAP *********************************************************************
localhost                  : ok=22   changed=11   unreachable=0    failed=0

```

main.yml testing
```
[root@rhel72 ansible]# ansible-playbook main.yml --extra-vars "github_key_file=~/github.pem"

...

TASK [base : Clone the project repos from Git] *********************************
changed: [localhost] => (item={u'repo': u'git@github.com:csc/wiley.git', u'name': u'wiley'})
changed: [localhost] => (item={u'repo': u'git@github.com:csc/slimer.git', u'name': u'slimer'})
changed: [localhost] => (item={u'repo': u'git@github.com:csc/ansible-scaleio.git', u'name': u'ansible-scaleio'})

TASK [base : Checkout the latest tagged version] *******************************
changed: [localhost] => (item={u'repo': u'git@github.com:csc/wiley.git', u'name': u'wiley'})
changed: [localhost] => (item={u'repo': u'git@github.com:csc/slimer.git', u'name': u'slimer'})
changed: [localhost] => (item={u'repo': u'git@github.com:csc/ansible-scaleio.git', u'name': u'ansible-scaleio'})

...

PLAY RECAP *********************************************************************
localhost                  : ok=51   changed=36   unreachable=0    failed=0
```

### CODE REVIEW

**Comment by jcpowermac** [comment]
Reviewed with @mtnbikenc :+1:

**Comment by adean20csc** [comment]
Good :+1:

**Comment by jdextercsc** [comment]
:+1:

**Comment by wgd3** [comment]
:+1:

**Pull request merged**
