### PR TITLE
Adding installation script to support Ansible 2.0

### PR DESCRIPTION
**Pull request by mtnbikenc**
This script will perform the necessary steps to deploy a kragle build.
Ansible 2.0 is cloned and an RPM is built to install a current version.

Testing was performed by walking through the test for PR #71.

NOTE: This PR requires PR #71.

### CODE REVIEW

**Comment by jcpowermac** [comment]
Reviewed with @mtnbikenc :+1:

**Comment by jdextercsc** [comment]
:+1:

**Comment by adean20csc** [comment]
Good :+1:

**Comment by wgd3** [comment]
:+1:

**Pull request merged**
